# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDTypedDefault(type=42), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarkovChain',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDTypedDefault(type=42), editable=False, primary_key=True, serialize=False, unique=True)),
                ('json_file', models.FileField(blank=True, null=True, upload_to='chains')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDTypedDefault(type=42), editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('last_post_datetime', models.DateTimeField(blank=True, null=True)),
                ('bots', models.ManyToManyField(related_name='accounts', to='bot.Bot')),
                ('markov_chain', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.MarkovChain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
