# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccountcorpus',
            name='markov_chain',
            field=models.FileField(blank=True, null=True, upload_to='chains'),
        ),
    ]
