# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_twitteraccountcorpus_markov_chain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwitterAccountCorpus',
            new_name='MarkovChain',
        ),
    ]
