# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20170918_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markovchain',
            old_name='markov_chain',
            new_name='json_file',
        ),
    ]
